@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class AbstractRepository<T> {
  + AbstractRepository():
  # defaultUpdateItem(T): void
  # defaultDeleteItem(String): void
  # defaultCreateItem(T): void
  # saveDatabase(): void
  + defaultViewOnlyDatabase(): Map<String, T>
  # loadDatabase(): void
  # defaultReadItem(String): T
}
class AdminAppointmentManager {
  + AdminAppointmentManager():
  + viewScheduledAppointments(AppointmentRepository): List<Appointment>
  + viewCompletedAppointments(AppointmentRepository): List<Appointment>
}
class AdminMenu {
  + AdminMenu(String, AppointmentRepository, StaffRepository, PatientRepository, MedicineRepository, UserRepository):
  + manageInventoryMenu(): void
  + userInterface(): void
  + viewAppointmentsMenu(AdminAppointmentManager): void
  + manageHospitalStaffMenu(): void
}
class Appointment {
  + Appointment():
  + Appointment(String, String, int, String):
  + diagnosis: String
  + prescription: String
  + timeToDisplayString(String): String
  + prescriptionIdToString(): String
   prescription: String
   ID: String
   diagnosis: String
}
class AppointmentRepository {
  + AppointmentRepository(String):
  + deleteAppointment(String): void
  + updateAppointment(String, String, String, Integer, Integer, String, String): void
  + completeAppointment(String, String, String, Integer): void
  + prescribeMedicine(String): boolean
  + printAllAppointments(): void
  + filterAppointments(String, String, Integer, String, Integer): List<Appointment>
  + createNewAppointment(String, String, int, String): boolean
}
class CSVHandler {
  + CSVHandler():
  + readHeaders(String): List<String>
  - writeLine(BufferedWriter, List<String>): void
  + writeToFile(String, List<String>, List<List<String>>): void
  + readRows(String): List<List<String>>
  - parseLine(String): List<String>
}
class DBLoader {
  + DBLoader():
  + loadCSV(String, Class<T>): HashMap<String, T>
  + saveCSV(String, HashMap<String, T>): void
}
class DateTimeHandler {
  + DateTimeHandler():
  + isValid(String): boolean
}
class DoctorAppointmentManager {
  + DoctorAppointmentManager():
  + createAppointment(AppointmentRepository, String, String, String, int): boolean
  + patientsUnderCare(AppointmentRepository, String): Set<String>
  + acceptAppointment(AppointmentRepository, String): void
  + checkBooked(AppointmentRepository, String): List<Appointment>
  + declineAppointment(AppointmentRepository, String): void
  + completeAppointment(AppointmentRepository, String, String, String, Integer): void
  + checkPending(AppointmentRepository, String): List<Appointment>
  + viewLeaves(AppointmentRepository, String): List<Appointment>
}
class DoctorMenu {
  + DoctorMenu(AppointmentRepository, StaffRepository, String, UserRepository, PatientRepository):
  - viewPersonalSchedule(DoctorAppointmentManager, AppointmentRepository, String): void
  - viewPatientMedicalRecords(DoctorAppointmentManager, PatientRepository, String): void
  + createAppointments(DoctorAppointmentManager, AppointmentRepository, String): void
  - viewBookedAppointments(DoctorAppointmentManager, AppointmentRepository, String, DateTimeFormatter): void
  + userInterface(): void
  - updatePersonalSchedule(DoctorAppointmentManager, AppointmentRepository, String): void
  - handlePendingAppointments(DoctorAppointmentManager, AppointmentRepository, String, DateTimeFormatter): void
  - updatePatientMedicalRecord(DoctorAppointmentManager, PatientRepository, String): void
  - recordAppointmentOutcome(DoctorAppointmentManager, AppointmentRepository, PatientRepository, String, DateTimeFormatter): void
}
class GenericRepository<T> {
  + GenericRepository(Class<T>, String):
  # defaultCreateItem(T): void
  # defaultUpdateItem(T): void
  # defaultDeleteItem(String): void
  # defaultReadItem(String): T
  + defaultViewOnlyDatabase(): Map<String, T>
  # loadDatabase(): void
  # saveDatabase(): void
}
interface IdentifiedObject << interface >> {
   ID: String
}
class InputValidater {
  + InputValidater():
   validInteger: int
   validString: String
}
class Main {
  + Main():
  + main(String[]): void
  + f(String): String
}
class MainMenu {
  + MainMenu(String, String, String, String, String):
  - createNewDefaultUser(UserRepository): void
  + run(): void
}
class Medicine {
  + Medicine():
   ID: String
}
class MedicineRepository {
  + MedicineRepository(String):
  - printMedicineCollection(Collection<Medicine>): void
  + deregisterMedicine(String): void
  + viewReplenishmentRequests(): void
  + setRequest(String, boolean): boolean
  + printMedicineStatus(Medicine): void
  + registerMedicine(Medicine): void
  + defaultReplenish(String): boolean
  + viewMedicationInventory(): void
  + replenishAll(): void
  + setQuantity(String, int): void
  + setAlertLevel(String, int): boolean
  + getMedicineObject(String): Medicine
  + dispense(String, int): boolean
   alerts: Set<Medicine>
}
class Menu {
  + Menu(AppointmentRepository, UserRepository, String):
  + userInterface(): void
  + changePassword(): void
}
class MenuFactory {
  ~ MenuFactory(UserRepository, String, String, String, String):
  + createMenu(String, String): Menu
}
class PasswordHelper {
  + PasswordHelper():
  + hash(String): String
  + verify(String, String): boolean
  + passwordRuleValidator(String): boolean
}
class Patient {
  + Patient(String, String, String, int, String, int, boolean, String):
  + Patient():
  + toString(): String
   ID: String
}
class PatientAppointmentManager {
  + PatientAppointmentManager():
  + checkAvailability(AppointmentRepository): List<Appointment>
  + checkPending(AppointmentRepository, String): List<Appointment>
  + cancelAppointment(AppointmentRepository, String): void
  + checkBooked(AppointmentRepository, String): List<Appointment>
  + bookAppointment(AppointmentRepository, String, String): void
  + checkPastAppointments(AppointmentRepository, String): List<Appointment>
}
class PatientMenu {
  + PatientMenu(String, AppointmentRepository, StaffRepository, UserRepository, PatientRepository):
  - rescheduleAppointment(PatientAppointmentManager): void
  - viewMedicalRecord(Patient): void
  - viewScheduledAppointments(PatientAppointmentManager): void
  - selectAppointment(List<Appointment>): int
  - viewAvailableAppointments(PatientAppointmentManager): void
  - scheduleAppointment(PatientAppointmentManager): void
  - updatePersonalInformation(Patient): void
  - viewPastAppointmentRecords(PatientAppointmentManager): void
  - cancelAppointment(PatientAppointmentManager): void
  - displayAppointments(List<Appointment>): void
  + userInterface(): void
}
class PatientRepository {
  + PatientRepository(String):
  + getPatient(String): Patient
  + updatePastDiagnoses(String, String): void
  + updateCurrentTreatmentPlan(String, String): void
  + filterPatients(String, String, String, Integer, Boolean, String, Integer, String, String, String): List<Patient>
  + deletePatient(String): void
  + updatePhoneNumber(String, int): void
  + updatePatient(String, String, String, Integer, Boolean, String, Integer, String, String, String): void
  + createNewPatient(String, String, String, int, String, int, Boolean, String): boolean
  + updateEmail(String, String): void
  + getName(String): String
}
class PharmacistAppointmentManager {
  + PharmacistAppointmentManager():
  + checkOutstandingRecords(AppointmentRepository): List<Appointment>
  + checkOutcomeRecord(AppointmentRepository, String): List<Appointment>
}
class PharmacistMenu {
  + PharmacistMenu(MedicineRepository, AppointmentRepository, UserRepository, String):
  - updatePrescriptionStatus(String): boolean
  + userInterface(): void
  - submitReplenishmentRequest(String): boolean
  - printAppointments(List<Appointment>): void
}
interface ResourceHandler << interface >> {
  + writeToFile(String, List<String>, List<List<String>>): void
  + readHeaders(String): List<String>
  + readRows(String): List<List<String>>
}
class Staff {
  + Staff():
  + Staff(String, String, String, int, boolean):
  + displayGender(): String
   ID: String
}
class StaffRepository {
  + StaffRepository(String):
  + getStaff(String): Staff
  + filterStaff(String, String, String, Integer, Boolean): List<Staff>
  + getName(String): String
  + updateStaff(String, String, String, Integer, Boolean): void
  + createNewStaff(String, String, String, int, Boolean): boolean
  + deleteStaff(String): void
}
class User {
  + User(String, String, String):
  + User():
   ID: String
}
class UserRepository {
  + UserRepository(String):
  + getUserRole(String): String
  + createNewUser(String, String, String): boolean
  + deleteUser(String): void
  + getUserObject(String): User
  + updateUserPassword(String, String): boolean
}

AdminAppointmentManager       -[#595959,dashed]->  Appointment
AdminAppointmentManager       -[#595959,dashed]->  AppointmentRepository
AdminMenu                     -[#595959,dashed]->  AdminAppointmentManager      : "«create»"
AdminMenu                     -[#595959,dashed]->  Appointment
AdminMenu                     -[#595959,dashed]->  AppointmentRepository
AdminMenu                     -[#595959,dashed]->  GenericRepository
AdminMenu                     -[#595959,dashed]->  InputValidater
AdminMenu                     -[#595959,dashed]->  Medicine                     : "«create»"
AdminMenu                    "1" *-[#595959,plain]-> "medRepo\n1" MedicineRepository
AdminMenu                     -[#000082,plain]-^  Menu
AdminMenu                    "1" *-[#595959,plain]-> "patRepo\n1" PatientRepository
AdminMenu                     -[#595959,dashed]->  Staff
AdminMenu                    "1" *-[#595959,plain]-> "staffRepo\n1" StaffRepository
AdminMenu                     -[#595959,dashed]->  UserRepository
Appointment                   -[#008200,dashed]-^  IdentifiedObject
AppointmentRepository         -[#595959,dashed]->  Appointment                  : "«create»"
AppointmentRepository         -[#595959,dashed]->  DateTimeHandler
AppointmentRepository         -[#000082,plain]-^  GenericRepository
CSVHandler                    -[#008200,dashed]-^  ResourceHandler
DBLoader                      -[#595959,dashed]->  CSVHandler                   : "«create»"
DBLoader                     "1" *-[#595959,plain]-> "resourceHandler\n1" ResourceHandler
DoctorAppointmentManager      -[#595959,dashed]->  Appointment
DoctorAppointmentManager      -[#595959,dashed]->  AppointmentRepository
DoctorMenu                    -[#595959,dashed]->  Appointment
DoctorMenu                    -[#595959,dashed]->  AppointmentRepository
DoctorMenu                    -[#595959,dashed]->  DateTimeHandler
DoctorMenu                    -[#595959,dashed]->  DoctorAppointmentManager     : "«create»"
DoctorMenu                    -[#595959,dashed]->  InputValidater
DoctorMenu                    -[#000082,plain]-^  Menu
DoctorMenu                    -[#595959,dashed]->  Patient
DoctorMenu                   "1" *-[#595959,plain]-> "patientRepo\n1" PatientRepository
DoctorMenu                   "1" *-[#595959,plain]-> "staffRepo\n1" StaffRepository
DoctorMenu                    -[#595959,dashed]->  UserRepository
GenericRepository             -[#000082,plain]-^  AbstractRepository
GenericRepository             -[#595959,dashed]->  DBLoader
GenericRepository             -[#595959,dashed]->  IdentifiedObject
Main                          -[#595959,dashed]->  MainMenu                     : "«create»"
MainMenu                      -[#595959,dashed]->  GenericRepository
MainMenu                      -[#595959,dashed]->  InputValidater
MainMenu                      -[#595959,dashed]->  Menu
MainMenu                      -[#595959,dashed]->  MenuFactory                  : "«create»"
MainMenu                      -[#595959,dashed]->  PasswordHelper
MainMenu                      -[#595959,dashed]->  User
MainMenu                      -[#595959,dashed]->  UserRepository               : "«create»"
Medicine                      -[#008200,dashed]-^  IdentifiedObject
MedicineRepository            -[#000082,plain]-^  GenericRepository
MedicineRepository           "1" *-[#595959,plain]-> "alertedMedicines\n*" Medicine
Menu                         "1" *-[#595959,plain]-> "apptRepo\n1" AppointmentRepository
Menu                          -[#595959,dashed]->  InputValidater
Menu                          -[#595959,dashed]->  PasswordHelper
Menu                          -[#595959,dashed]->  User
Menu                         "1" *-[#595959,plain]-> "userRepo\n1" UserRepository
MenuFactory                   -[#595959,dashed]->  AdminMenu                    : "«create»"
MenuFactory                   -[#595959,dashed]->  AppointmentRepository        : "«create»"
MenuFactory                  "1" *-[#595959,plain]-> "apptRepo\n1" AppointmentRepository
MenuFactory                   -[#595959,dashed]->  DoctorMenu                   : "«create»"
MenuFactory                   -[#595959,dashed]->  GenericRepository
MenuFactory                   -[#595959,dashed]->  MedicineRepository           : "«create»"
MenuFactory                  "1" *-[#595959,plain]-> "medRepo\n1" MedicineRepository
MenuFactory                   -[#595959,dashed]->  Menu
MenuFactory                   -[#595959,dashed]->  PatientMenu                  : "«create»"
MenuFactory                   -[#595959,dashed]->  PatientRepository            : "«create»"
MenuFactory                  "1" *-[#595959,plain]-> "patientRepo\n1" PatientRepository
MenuFactory                   -[#595959,dashed]->  PharmacistMenu               : "«create»"
MenuFactory                   -[#595959,dashed]->  StaffRepository              : "«create»"
MenuFactory                  "1" *-[#595959,plain]-> "staffRepo\n1" StaffRepository
MenuFactory                  "1" *-[#595959,plain]-> "userRepo\n1" UserRepository
Patient                       -[#008200,dashed]-^  IdentifiedObject
PatientAppointmentManager     -[#595959,dashed]->  Appointment
PatientAppointmentManager     -[#595959,dashed]->  AppointmentRepository
PatientMenu                   -[#595959,dashed]->  Appointment
PatientMenu                   -[#595959,dashed]->  AppointmentRepository
PatientMenu                   -[#595959,dashed]->  InputValidater
PatientMenu                   -[#000082,plain]-^  Menu
PatientMenu                   -[#595959,dashed]->  Patient
PatientMenu                   -[#595959,dashed]->  PatientAppointmentManager    : "«create»"
PatientMenu                  "1" *-[#595959,plain]-> "patientRepo\n1" PatientRepository
PatientMenu                  "1" *-[#595959,plain]-> "staffRepo\n1" StaffRepository
PatientMenu                   -[#595959,dashed]->  UserRepository
PatientRepository             -[#000082,plain]-^  GenericRepository
PatientRepository             -[#595959,dashed]->  Patient                      : "«create»"
PharmacistAppointmentManager  -[#595959,dashed]->  Appointment
PharmacistAppointmentManager  -[#595959,dashed]->  AppointmentRepository
PharmacistMenu                -[#595959,dashed]->  Appointment
PharmacistMenu                -[#595959,dashed]->  AppointmentRepository
PharmacistMenu                -[#595959,dashed]->  InputValidater
PharmacistMenu                -[#595959,dashed]->  Medicine
PharmacistMenu               "1" *-[#595959,plain]-> "medRepo\n1" MedicineRepository
PharmacistMenu                -[#000082,plain]-^  Menu
PharmacistMenu                -[#595959,dashed]->  PharmacistAppointmentManager : "«create»"
PharmacistMenu               "1" *-[#595959,plain]-> "pharmacistAppointmentManager\n1" PharmacistAppointmentManager
PharmacistMenu                -[#595959,dashed]->  UserRepository
Staff                         -[#008200,dashed]-^  IdentifiedObject
StaffRepository               -[#000082,plain]-^  GenericRepository
StaffRepository               -[#595959,dashed]->  Staff                        : "«create»"
User                          -[#008200,dashed]-^  IdentifiedObject
User                          -[#595959,dashed]->  PasswordHelper
UserRepository                -[#000082,plain]-^  GenericRepository
UserRepository                -[#595959,dashed]->  PasswordHelper
UserRepository                -[#595959,dashed]->  User                         : "«create»"
@enduml
